version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.3
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=sssss
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql

  devops-back:
    depends_on:
      - mysqldb
    image: oudaybenmessaoud/ouday-5se1-g4-projet4:nazih
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/sssss?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "ouday",
        "spring.datasource.password" : "rootpassword",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
    command: >
      bash -c "
        echo 'Waiting 60 seconds for MySQL to be ready...';
        sleep 60;
        echo 'Starting Spring Boot application...';
        java -jar /app.jar
      "

volumes:
  db:
