version: '3.8'

services:
  # Service MySQL
  mysqldb:
    image: mysql:8.0
    container_name: mysqldb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=YES
      - MYSQL_DATABASE=db
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  # Service Spring Boot (devops-back)
  devops-back:
    depends_on:
      - mysqldb  # Dépendance explicite pour garantir que MySQL démarre avant l'application
    build:
      context: .
      dockerfile: Dockerfile
    container_name: devops-back
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_JSON: |
        {
          "spring.datasource.url": "jdbc:mysql://mysqldb:3306/db?useUnicode=true&useJDBCCompliantTimezoneShift=true&createDatabaseIfNotExist=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
          "spring.datasource.username": "root",
          "spring.datasource.password": "YES",
          "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL5InnoDBDialect",
          "spring.jpa.hibernate.ddl-auto": "update"
        }
    stdin_open: true
    tty: true
    networks:
      - backend
    command: >
      bash -c "until nc -z mysqldb 3306; do echo 'Waiting for MySQL...'; sleep 3; done;
      java -jar /app.jar"

volumes:
  db:

networks:
  backend:
    driver: bridge
