version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.3
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  devops-back:
    depends_on:
      - mysqldb
    image: oudaybenmessaoud/ouday-5se1-g4-projet4:null
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db:
    driver: local