version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.30
    restart: unless-stopped
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  devops-back:
    depends_on:
      - mysqldb
    image: aniskh643/anis-5se1-g4-projet4:null
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true",
      "spring.datasource.username" : "root",
      "spring.datasource.password" : "",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
      "spring.jpa.hibernate.ddl-auto" : "update"
    }'
    stdin_open: true
    tty: true

  nexus:
    container_name: 5se1-groupe4-projet4-nexus-1
    image: sonatype/nexus3
    restart: unless-stopped
    ports:
      - 8082:8081
    volumes:
      # Reusing the existing Nexus volume
      - bcc76edebb552a673bf426bbd77c0881ee8aaa54b1dcaf68466459b5a57e12a7:/nexus-data

  sonarqube:
    container_name: 5se1-groupe4-projet4-sonarqube-1
    image: sonarqube:9.4-community
    restart: unless-stopped
    ports:
      - 9000:9000
    environment:
      - SONAR_JDBC_URL=jdbc:mysql://mysqldb:3306/db
      - SONAR_JDBC_USERNAME=root
      - SONAR_JDBC_PASSWORD=
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  db:
  bcc76edebb552a673bf426bbd77c0881ee8aaa54b1dcaf68466459b5a57e12a7:
    external: true
  sonarqube_data:
    external: true
  sonarqube_logs:
    external: true
  sonarqube_extensions:
    external: true
