version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/sssss?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ouday
      SPRING_DATASOURCE_PASSWORD: ouday
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
    networks:
      - mynetworkouday

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.33  # Mise à jour vers la version 8.0.33
    volumes:
      - /home/ubuntu/Desktop/db:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: sssss
      MYSQL_USER: ouday
      MYSQL_PASSWORD: ouday
      MYSQL_ROOT_PASSWORD: ouday
    networks:
      - mynetworkouday

networks:
  mynetworkouday:
    driver: bridge
