version: "3.8"
services:

  # database application service
  mysqldb:
    image: mysql:8.0.3
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db:/var/lib/mysql

    # backend application service
  invoice-backend:
    depends_on:
      - mysqldb
    image: oudaybenmessaoud/ouday-5se1-g4-projet4:v10.0.0  # Remplacez par l'image correcte

    build: ./
    restart: on-failure
    ports:
      - 8087:8087

    stdin_open: true
    tty: true
    environment:

      SPRING APPLICATION_JSON: '{
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/invoicedb?createDatabaseIfNotExist=true",
        "spring.datasource.username": "root",
        "spring.datasource.password": null,
        "spring.jpa.properties.hibernate.dialect":"org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto": "update"
      }'
  # Frontend application service


volumes:
  db :