version: "3.8"

services:
  mysqldb:
    image: mysql:8.1.1
    container_name: ouday
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
    networks:
        - mynetwork
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  devops-back:
    depends_on:
      - mysqldb
    image: oudaybenmessaoud/ouday-5se1-g4-projet4:latest
    # Uncomment if you need to build locally instead of using the image
    # build: ./
    restart: on-failure
    ports:
      - 7070:8089
    networks:
          - mynetwork

volumes:
  mysql_data :
networks:
      mynetwork:
        driver: bridge

