version: "3.8"  # Docker Compose version

services:
  # Server service
  server:
    build: .  # Use the Dockerfile in the current directory to build the server image
    restart: always  # Restart the container automatically if it stops
    ports:
      - "8089:8089"  # Map port 8080 on the host to port 8080 in the container
    environment:  # Environment variables for connecting to the MySQL database
      MYSQL_DATABASE: ddddddddddddd
      MYSQL_USER: ouday
      MYSQL_PASSWORD: ouday
      MYSQL_ROOT_PASSWORD: ouday
    depends_on:
      - mysqldb  # Ensure that the MySQL database service starts before the server

  # MySQL database service
  mysqldb:
    image: "mysql:8.0.3"  # MySQL version 8.0.3
    restart: always  # Restart the container automatically if it stops
    ports:
      - "3307:3306"  # Map port 3307 on the host to MySQL's default port 3306 in the container
    environment:  # Environment variables to configure the MySQL database
      MYSQL_DATABASE: ddddddddddddd
      MYSQL_USER: ouday
      MYSQL_PASSWORD: ouday
      MYSQL_ROOT_PASSWORD: ouday
