version: "3.8"

services:
  mysqldb:
    image: mysql:8.1.1  # Utilisation de MySQL 8.1.1
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=  # Mot de passe pour l'utilisateur root
      - MYSQL_DATABASE=db     # Création de la base de données 'db' si elle n'existe pas
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  devops-back:
    depends_on:
      - mysqldb
    image: oudaybenmessaoud/ouday-5se1-g4:latest
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",  # Dialecte pour MySQL 8.x
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

volumes:
  db: