version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.30
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  devops-back:
    depends_on:
      - mysqldb
    image: aniskh643/anis-5se1-g4-projet4:null
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "raoot",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true

  nexus:
    image: sonatype/nexus3
    restart: unless-stopped
    ports:
      - 8082:8081  # Ensure port mapping matches the existing container
    volumes:
      - nexus-data:/nexus-data

  sonarqube:
    image: sonarqube:latest
    restart: unless-stopped
    ports:
      - 9001:9000  # Ensure port mapping matches the existing container
    environment:
      - SONAR_JDBC_URL=jdbc:mysql://mysqldb:3306/db
      - SONAR_JDBC_USERNAME=root
      - SONAR_JDBC_PASSWORD=
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_extensions:/opt/sonarqube/extensions

volumes:
  db:
  nexus-data:
  sonarqube_data:
  sonarqube_logs:
  sonarqube_extensions: