version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ""  # Utiliser un mot de passe vide pour root
      MYSQL_DATABASE: sssss
    ports:
      - "3306:3306"
    volumes:
      - /home/ubuntu/Desktop/db:/var/lib/mysql  # Persiste les données sur l'hôte
    networks:
      - mynetworkouday
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  server:
    container_name: springboot
    image: oudaybenmessaoud/ouday-5se1-g4-projet4:latest  # Image Spring Boot spécifique
    restart: always
    depends_on:
      - mysqldb  # Assure que mysqldb soit démarré avant Spring Boot
    ports:
      - "8082:8082"  # Expose Spring Boot sur le port 8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/sssss?createDatabaseIfNotExist=true&useSSL=false&requireSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""  # Aucun mot de passe pour root
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
    networks:
      - mynetworkouday
    command: >
      bash -c "
        until mysql -h mysqldb -u root -e 'SELECT 1'; do
          echo 'En attente de MySQL...';
          sleep 5;
        done;
        echo 'MySQL est prêt. Démarrage de Spring Boot...';
        java -jar /app.jar
      "

networks:
  mynetworkouday:
    driver: bridge
