version: '3.8'

services:
  mysqldb:
    image: mysql:8.0.3
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword  # Mot de passe root pour MySQL
      - MYSQL_DATABASE=sssss              # Base de données à créer
    ports:
      - 3308:3306
    volumes:
      - ./db:/var/lib/mysql               # Volume pour la persistance des données
    networks:
      - app-network

  devops-back:
    depends_on:
      - mysqldb
    image: oudaybenmessaoud/ouday-5se1-g4-projet4:v1.0.0  # Utilisation du tag v1.0.0
    ports:
      - 8082:8082                          # Port exposé pour Spring Boot
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port": "8082",
        "spring.datasource.url": "jdbc:mysql://mysqldb:3306/sssss?createDatabaseIfNotExist=true&useSSL=false&requireSSL=false",
        "spring.datasource.username": "root",
        "spring.datasource.password": "rootpassword",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto": "update",
        "spring.datasource.initialization-mode": "always",
        "spring.datasource.platform": "mysql"
      }'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
