version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/sssss?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ouday
      SPRING_DATASOURCE_PASSWORD: ouday
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
    networks:
      - mynetworkouday
    command: ["sh", "-c", "sleep 60 && java -jar /app.jar"]  # Sleep 30 secondes avant de démarrer Spring Boot

  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.3
    volumes:
      - /home/ubuntu/Desktop/db:/var/lib/mysql  # Stockage des données sur l'hôte
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: sssss
      MYSQL_USER: ouday
      MYSQL_PASSWORD: ouday
      MYSQL_ROOT_PASSWORD: ouday
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=ouday"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s
    networks:
      - mynetworkouday

# Définition du réseau personnalisé
networks:
  mynetworkouday:
    driver: bridge
