version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.3
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD:Admin
      - MYSQL_DATABASE:db
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql

  devops-back:
    depends_on:
      - mysqldb
    image: oudaybenmessaoud/ouday-5se1-g4-projet4:latest
    # Uncomment if you need to build locally instead of using the image
    # build: ./
    restart: on-failure
    ports:
      - 8082:8082
    environment:
      SPRING_APPLICATION_JSON: '{
             "spring.datasource.url": "jdbc:mysql://mysqldb:3306/db?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC",
             "spring.datasource.username": "root",
             "spring.datasource.password": "Admin",
             "spring.jpa.properties.hibernate.dialect": "org.hibernate.dialect.MySQLDialect",
             "spring.jpa.hibernate.ddl-auto": "update",
             "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
             "spring.jpa.hibernate.ddl-auto": "update",
             "spring.datasource.initialization-mode": "always",
             "spring.datasource.platform": "mysql"
           }'
    stdin_open: true
    tty: true


volumes:
  db:
    driver: local

