version: "3.8"
services:
  server:
    build: .
    restart: always
    ports:
      - "8700:8700"
    depends_on:
      - mysqldb
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.3
    restart: always
    volumes:
      - /home/ubuntu/Desktop/db:/var/lib/mysql  # Stockage des données sur l'hôte
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: sssss
      MYSQL_USER: ouday
      MYSQL_PASSWORD: ouday
      MYSQL_ROOT_PASSWORD: ouday
