version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.3
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=sssss
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql

  devops-back:
    depends_on:
      - mysqldb
    image: oudaybenmessaoud/ouday-5se1-g4-projet4:laert
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "server.port": "8089",
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/sssss?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.datasource.driver-class-name": "com.mysql.cj.jdbc.Driver",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
        "spring.datasource.initialization-mode": "always",
        "spring.datasource.platform": "mysql"
      }'
    stdin_open: true
    tty: true
    command: >
      bash -c "
        echo 'Waiting 60 seconds for MySQL to be ready...';
        sleep 60;
        echo 'Starting Spring Boot application...';
        java -jar /app.jar
      "

volumes:
  db:
