version: "3.8"

services:
  mysqldb:
    image: mysql:8.0.3
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=sssss
    ports:
      - 3306:3306
    volumes:
      - /home/ubuntu/Desktop/db:/var/lib/mysql

  devops-back:
    depends_on:
      - mysqldb
    image: oudaybenmessaoud/ouday-5se1-g4-projet4:latest
    restart: on-failure
    ports:
      - 8089:8089
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:3306/sssss?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
    command: >
      bash -c "
        echo 'Attente de 60 secondes pour que MySQL soit prêt...';
        sleep 60;
        echo 'Démarrage de l'application Spring Boot...';
        java -jar /app.jar
      "

volumes:
  db: