version: "3.8"

services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.3
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ouday
      MYSQL_DATABASE: sssss
      MYSQL_USER: ouday
      MYSQL_PASSWORD: ouday
    ports:
      - "3307:3306"  # Expose MySQL on port 3307 of your machine
    volumes:
      - /home/ubuntu/Desktop/db:/var/lib/mysql  # Persist data to the host
    networks:
      - mynetworkouday
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--host=localhost", "--user=root", "--password=ouday"]
      interval: 10s
      retries: 5
      start_period: 10s
      timeout: 5s

  server:
    container_name: springboot
    image: oudaybenmessaoud/ouday-5se1-g4-projet4:latest  # Image Spring Boot spécifique
    restart: always
    depends_on:
      - mysqldb  # Assure que mysqldb soit démarré avant le Spring Boot
    ports:
      - "8082:8082"  # Expose Spring Boot sur le port 8082
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/sssss?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ouday
      SPRING_DATASOURCE_PASSWORD: ouday
      SPRING_DATASOURCE_DRIVER-CLASS-NAME: com.mysql.cj.jdbc.Driver
    networks:
      - mynetworkouday
    command: ["sh", "-c", "sleep 120 && java -jar /app.jar"]  # Sleep 120 secondes avant de démarrer Spring Boot

networks:
  mynetworkouday:
    driver: bridge
